from xacc/build_manylinux_wheels
run wget https://raw.githubusercontent.com/ORNL-QCI/xacc-rigetti/master/tools/wheels/build_rigetti_manylinux_wheels.sh --no-check-certificate && sh build_rigetti_manylinux_wheels.sh
