from xacc/build_manylinux_wheels
run wget https://raw.githubusercontent.com/ornl-qci/xacc-vqe/mccaskey/cpr_build/tools/wheels/build_xacc_vqe_manylinux_wheels.sh --no-check-certificate && sh build_xacc_vqe_manylinux_wheels.sh
