from xacc/build_manylinux_wheels
run wget https://raw.githubusercontent.com/ORNL-QCI/xacc-ibm/master/tools/wheels/build_ibm_manylinux_wheels.sh --no-check-certificate && sh build_ibm_manylinux_wheels.sh
