from xacc/build_manylinux_wheels
run yum -y install blas-devel lapack-devel && wget https://raw.githubusercontent.com/ornl-qci/tnqvm/master/tools/wheels/build_tnqvm_manylinux_wheels.sh --no-check-certificate && sh build_tnqvm_manylinux_wheels.sh
