from xacc/manylinux1_x86_64
run wget https://raw.githubusercontent.com/eclipse/xacc/mccaskey/cpr_build/tools/wheels/build_xacc_manylinux_wheels.sh --no-check-certificate && sh build_xacc_manylinux_wheels.sh
